# Generated by Django 3.2.2 on 2022-02-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='Actimg',
            field=models.ImageField(blank=True, null=True, upload_to='activities/images'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='Actreport',
            field=models.FileField(blank=True, null=True, upload_to='activities/reports'),
        ),
    ]
