# Generated by Django 3.2.2 on 2022-02-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proctor', '0002_auto_20220207_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplementary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USN', models.CharField(blank=True, max_length=10, null=True)),
                ('Name', models.TextField(blank=True, max_length=70, null=True)),
                ('EmailId', models.EmailField(blank=True, max_length=100, null=True)),
                ('Semester', models.IntegerField(default=0)),
                ('Courses', models.CharField(blank=True, max_length=100, null=True)),
                ('Course1', models.TextField(blank=True, max_length=34, null=True)),
                ('Course2', models.TextField(blank=True, max_length=34, null=True)),
                ('Course3', models.TextField(blank=True, max_length=34, null=True)),
                ('Course4', models.TextField(blank=True, max_length=34, null=True)),
                ('Course5', models.TextField(blank=True, max_length=34, null=True)),
                ('Course6', models.TextField(blank=True, max_length=34, null=True)),
                ('Course7', models.TextField(blank=True, max_length=34, null=True)),
                ('Course8', models.TextField(blank=True, max_length=34, null=True)),
                ('Course9', models.TextField(blank=True, max_length=34, null=True)),
                ('Course10', models.TextField(blank=True, max_length=34, null=True)),
                ('SGPA', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='Semester1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Semester2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Semester3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Semester4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Semester5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Semester6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Semester7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Semester8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
