# Generated by Django 3.2.2 on 2022-02-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proctor', '0004_activities_reject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmailId', models.EmailField(blank=True, max_length=100, null=True)),
                ('Name', models.TextField(blank=True, max_length=70, null=True)),
                ('Bugdesc', models.TextField(blank=True, max_length=300, null=True)),
                ('Priority', models.TextField(blank=True, max_length=10, null=True)),
                ('Bugimg', models.ImageField(blank=True, null=True, upload_to='bugs')),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmailId', models.EmailField(blank=True, max_length=100, null=True)),
                ('USN', models.CharField(blank=True, max_length=10, null=True)),
                ('Rec', models.TextField(blank=True, max_length=10, null=True)),
                ('Other', models.TextField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
