# Generated by Django 3.2.2 on 2022-02-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proctor', '0005_bugs_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
