# Generated by Django 3.2.2 on 2022-02-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proctor', '0006_requests_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='semrec1',
            name='Result',
            field=models.FileField(blank=True, null=True, upload_to='results'),
        ),
        migrations.AddField(
            model_name='semrec2',
            name='Result',
            field=models.FileField(blank=True, null=True, upload_to='results'),
        ),
        migrations.AddField(
            model_name='semrec3',
            name='Result',
            field=models.FileField(blank=True, null=True, upload_to='results'),
        ),
        migrations.AddField(
            model_name='semrec4',
            name='Result',
            field=models.FileField(blank=True, null=True, upload_to='results'),
        ),
        migrations.AddField(
            model_name='semrec5',
            name='Result',
            field=models.FileField(blank=True, null=True, upload_to='results'),
        ),
        migrations.AddField(
            model_name='semrec6',
            name='Result',
            field=models.FileField(blank=True, null=True, upload_to='results'),
        ),
        migrations.AddField(
            model_name='semrec7',
            name='Result',
            field=models.FileField(blank=True, null=True, upload_to='results'),
        ),
        migrations.AddField(
            model_name='semrec8',
            name='Result',
            field=models.FileField(blank=True, null=True, upload_to='results'),
        ),
        migrations.AddField(
            model_name='supplementary',
            name='Result',
            field=models.FileField(blank=True, null=True, upload_to='results'),
        ),
    ]
